# Development override for docker-compose.yml
# This file enables live code reloading for development

version: '3.8'

services:
  a2a-server:
    # Override the build with volume mounts for development
    volumes:
      # Mount source code for live reloading
      - ./a2a-server/src:/app/src:ro
      - ./a2a-server/package.json:/app/package.json:ro
      - ./a2a-server/package-lock.json:/app/package-lock.json:ro
      - ./a2a-server/tsconfig.json:/app/tsconfig.json:ro
      - ./a2a-server/node_modules:/app/node_modules:ro
    # Use TypeScript compilation for development
    command: >
      sh -c "
        echo 'Installing dependencies for development...'
        npm install
        echo 'Compiling TypeScript...'
        npm run build
        echo 'Starting development server...'
        node dist/server.js
      "
    # Enable file watching
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    # Restart policy for development
    restart: unless-stopped 