services:
  postgres:
    image: postgres:14.13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: welcome123
      POSTGRES_DB: platform

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "11000:11000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 11000
    command: start-dev --import-realm
    entrypoint: |
      /bin/sh -c "
      /opt/keycloak/bin/kc.sh import --file /tmp/keycloak-complete-realm.json
      exec /opt/keycloak/bin/kc.sh start-dev
      "
    volumes:
      - ./keycloak-complete-realm.json:/tmp/keycloak-complete-realm.json:ro

  engine:
    image: ghcr.io/noumenadigital/images/engine:latest
    depends_on:
      - postgres
    ports:
      - "12000:12000"
      - "12400:12400"
      - "12700:12700"
    environment:
      ENGINE_DB_URL: "jdbc:postgresql://postgres:5432/platform"
      ENGINE_DB_USER: postgres
      ENGINE_DB_PASSWORD: welcome123
      ENGINE_DB_SCHEMA: engine-schema
      ENGINE_ALLOWED_ISSUERS: "http://keycloak:11000/realms/noumena"
      SWAGGER_SECURITY_AUTH_URL: "http://localhost:11000/realms/noumena"
      SWAGGER_SECURITY_CLIENT_ID: "noumena"
